/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as MarketplaceIndexImport } from './routes/marketplace/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as RegisterUiImport } from './routes/register/ui'
import { Route as MarketplacePoolIdIndexImport } from './routes/marketplace/$poolId/index'
import { Route as DashboardDoctorIndexImport } from './routes/dashboard/doctor/index'
import { Route as DashboardPatientIdIndexImport } from './routes/dashboard/$patientId/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceIndexRoute = MarketplaceIndexImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterUiRoute = RegisterUiImport.update({
  id: '/register/ui',
  path: '/register/ui',
  getParentRoute: () => rootRoute,
} as any)

const MarketplacePoolIdIndexRoute = MarketplacePoolIdIndexImport.update({
  id: '/marketplace/$poolId/',
  path: '/marketplace/$poolId/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDoctorIndexRoute = DashboardDoctorIndexImport.update({
  id: '/dashboard/doctor/',
  path: '/dashboard/doctor/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardPatientIdIndexRoute = DashboardPatientIdIndexImport.update({
  id: '/dashboard/$patientId/',
  path: '/dashboard/$patientId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/register/ui': {
      id: '/register/ui'
      path: '/register/ui'
      fullPath: '/register/ui'
      preLoaderRoute: typeof RegisterUiImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/$patientId/': {
      id: '/dashboard/$patientId/'
      path: '/dashboard/$patientId'
      fullPath: '/dashboard/$patientId'
      preLoaderRoute: typeof DashboardPatientIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/doctor/': {
      id: '/dashboard/doctor/'
      path: '/dashboard/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorIndexImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/$poolId/': {
      id: '/marketplace/$poolId/'
      path: '/marketplace/$poolId'
      fullPath: '/marketplace/$poolId'
      preLoaderRoute: typeof MarketplacePoolIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register/ui': typeof RegisterUiRoute
  '/dashboard': typeof DashboardIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/$patientId': typeof DashboardPatientIdIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/marketplace/$poolId': typeof MarketplacePoolIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register/ui': typeof RegisterUiRoute
  '/dashboard': typeof DashboardIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/$patientId': typeof DashboardPatientIdIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/marketplace/$poolId': typeof MarketplacePoolIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register/ui': typeof RegisterUiRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/$patientId/': typeof DashboardPatientIdIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/marketplace/$poolId/': typeof MarketplacePoolIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/register/ui'
    | '/dashboard'
    | '/marketplace'
    | '/register'
    | '/dashboard/$patientId'
    | '/dashboard/doctor'
    | '/marketplace/$poolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/register/ui'
    | '/dashboard'
    | '/marketplace'
    | '/register'
    | '/dashboard/$patientId'
    | '/dashboard/doctor'
    | '/marketplace/$poolId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/register/ui'
    | '/dashboard/'
    | '/marketplace/'
    | '/register/'
    | '/dashboard/$patientId/'
    | '/dashboard/doctor/'
    | '/marketplace/$poolId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RegisterUiRoute: typeof RegisterUiRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  DashboardPatientIdIndexRoute: typeof DashboardPatientIdIndexRoute
  DashboardDoctorIndexRoute: typeof DashboardDoctorIndexRoute
  MarketplacePoolIdIndexRoute: typeof MarketplacePoolIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RegisterUiRoute: RegisterUiRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  DashboardPatientIdIndexRoute: DashboardPatientIdIndexRoute,
  DashboardDoctorIndexRoute: DashboardDoctorIndexRoute,
  MarketplacePoolIdIndexRoute: MarketplacePoolIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/register/ui",
        "/dashboard/",
        "/marketplace/",
        "/register/",
        "/dashboard/$patientId/",
        "/dashboard/doctor/",
        "/marketplace/$poolId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/register/ui": {
      "filePath": "register/ui.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/marketplace/": {
      "filePath": "marketplace/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/dashboard/$patientId/": {
      "filePath": "dashboard/$patientId/index.tsx"
    },
    "/dashboard/doctor/": {
      "filePath": "dashboard/doctor/index.tsx"
    },
    "/marketplace/$poolId/": {
      "filePath": "marketplace/$poolId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
