/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as MarketplaceIndexImport } from './routes/marketplace/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as MarketplacePoolIdIndexImport } from './routes/marketplace/$poolId/index'
import { Route as DashboardAddIndexImport } from './routes/dashboard/add/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceIndexRoute = MarketplaceIndexImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const MarketplacePoolIdIndexRoute = MarketplacePoolIdIndexImport.update({
  id: '/marketplace/$poolId/',
  path: '/marketplace/$poolId/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAddIndexRoute = DashboardAddIndexImport.update({
  id: '/dashboard/add/',
  path: '/dashboard/add/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/add/': {
      id: '/dashboard/add/'
      path: '/dashboard/add'
      fullPath: '/dashboard/add'
      preLoaderRoute: typeof DashboardAddIndexImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/$poolId/': {
      id: '/marketplace/$poolId/'
      path: '/marketplace/$poolId'
      fullPath: '/marketplace/$poolId'
      preLoaderRoute: typeof MarketplacePoolIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/add': typeof DashboardAddIndexRoute
  '/marketplace/$poolId': typeof MarketplacePoolIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/register': typeof RegisterIndexRoute
  '/dashboard/add': typeof DashboardAddIndexRoute
  '/marketplace/$poolId': typeof MarketplacePoolIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/dashboard/add/': typeof DashboardAddIndexRoute
  '/marketplace/$poolId/': typeof MarketplacePoolIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/marketplace'
    | '/register'
    | '/dashboard/add'
    | '/marketplace/$poolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/marketplace'
    | '/register'
    | '/dashboard/add'
    | '/marketplace/$poolId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard/'
    | '/marketplace/'
    | '/register/'
    | '/dashboard/add/'
    | '/marketplace/$poolId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  DashboardAddIndexRoute: typeof DashboardAddIndexRoute
  MarketplacePoolIdIndexRoute: typeof MarketplacePoolIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  DashboardAddIndexRoute: DashboardAddIndexRoute,
  MarketplacePoolIdIndexRoute: MarketplacePoolIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dashboard/",
        "/marketplace/",
        "/register/",
        "/dashboard/add/",
        "/marketplace/$poolId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/marketplace/": {
      "filePath": "marketplace/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/dashboard/add/": {
      "filePath": "dashboard/add/index.tsx"
    },
    "/marketplace/$poolId/": {
      "filePath": "marketplace/$poolId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
